language: python
python: 
 - "3.5"
 - "pypy3"
before_install:
 - "sudo apt-get install python3-pyqt5"
 - "sudo pip3 install pyinstaller"
 - "pip3 install -r requirements.txt"
install: "pyinstaller --name 'Rocto Client' --onefile rocto_client/Qt/gui.py"
