version: 0.1.{build}
environment:
  matrix:
    - PYTHON: C:\\Python36
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    
    - PYTHON: C:\\Python36-x64
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - py --version
install:
  - py -m pip install -U pip 
  - py -m pip install pyinstaller==3.3
  - py -m pip install -r requirements.txt
  - set PATH=%PYTHON%\\Scripts;%PATH%
build_script:
  - call scripts/winbuild.bat
  - 7z a dist/rocto.zip dist/rocto/
artifacts:
  - path: dist/*
