version: 0.1.{build}
environment:
  matrix:
    - PYTHON: C:\\Python36
      PYTH: C:\\Python36\\python.exe
      PYINSTALLER: C:\\Python36\\Scripts\\pyinstaller.exe
      PYTHON_ARCH: "32"
    
    - PYTHON: C:\\Python36-x64
      PYTH: C:\\Python36-x64\\python.exe
      PYINSTALLER: C:\\Python36-x64\\Scripts\\pyinstaller.exe
      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON_ARCH%
  - call %PYTH% --version
  
install:
  - call %PYTH% -m pip install -U pip 
  - call %PYTH% -m pip install pyinstaller==3.3
  - call %PYTH% -m pip install -r requirements.txt
build_script:
  - call scripts/winbuild.bat
artifacts:
  - path: dist/*
