# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source/preferencesdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.setWindowModality(QtCore.Qt.NonModal)
        PreferencesDialog.setEnabled(True)
        PreferencesDialog.resize(657, 213)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        PreferencesDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PreferencesDialog.setWindowIcon(icon)
        PreferencesDialog.setWindowOpacity(1.0)
        PreferencesDialog.setAutoFillBackground(False)
        PreferencesDialog.setSizeGripEnabled(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(PreferencesDialog)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_buttons = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.settings_buttons.setAcceptDrops(False)
        self.settings_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.settings_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.settings_buttons.setCenterButtons(False)
        self.settings_buttons.setObjectName("settings_buttons")
        self.gridLayout_2.addWidget(self.settings_buttons, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.serv_tab = QtWidgets.QWidget()
        self.serv_tab.setObjectName("serv_tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.serv_tab)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.box_usersettings = QtWidgets.QGroupBox(self.serv_tab)
        self.box_usersettings.setObjectName("box_usersettings")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.box_usersettings)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.input_username = QtWidgets.QLineEdit(self.box_usersettings)
        self.input_username.setMinimumSize(QtCore.QSize(0, 0))
        self.input_username.setMaximumSize(QtCore.QSize(140, 16777215))
        self.input_username.setObjectName("input_username")
        self.gridLayout_6.addWidget(self.input_username, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.box_usersettings)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.box_usersettings)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.input_password = QtWidgets.QLineEdit(self.box_usersettings)
        self.input_password.setMinimumSize(QtCore.QSize(0, 0))
        self.input_password.setMaximumSize(QtCore.QSize(140, 16777215))
        self.input_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setProperty("clearButtonEnabled", False)
        self.input_password.setObjectName("input_password")
        self.gridLayout_6.addWidget(self.input_password, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.box_usersettings)
        self.box_serversettings = QtWidgets.QGroupBox(self.serv_tab)
        self.box_serversettings.setObjectName("box_serversettings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.box_serversettings)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.ip_label = QtWidgets.QLabel(self.box_serversettings)
        self.ip_label.setObjectName("ip_label")
        self.gridLayout.addWidget(self.ip_label, 0, 0, 1, 1)
        self.ip_entry = QtWidgets.QLineEdit(self.box_serversettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_entry.sizePolicy().hasHeightForWidth())
        self.ip_entry.setSizePolicy(sizePolicy)
        self.ip_entry.setMinimumSize(QtCore.QSize(15, 0))
        self.ip_entry.setObjectName("ip_entry")
        self.gridLayout.addWidget(self.ip_entry, 0, 1, 1, 2)
        self.port_label = QtWidgets.QLabel(self.box_serversettings)
        self.port_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 1, 0, 1, 1)
        self.port_entry = QtWidgets.QLineEdit(self.box_serversettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_entry.sizePolicy().hasHeightForWidth())
        self.port_entry.setSizePolicy(sizePolicy)
        self.port_entry.setMinimumSize(QtCore.QSize(80, 0))
        self.port_entry.setMaximumSize(QtCore.QSize(45, 16777215))
        self.port_entry.setObjectName("port_entry")
        self.gridLayout.addWidget(self.port_entry, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.box_serversettings)
        self.gridLayout_10.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.serv_tab, "")
        self.syst_tab = QtWidgets.QWidget()
        self.syst_tab.setObjectName("syst_tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.syst_tab)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.box_rsettings = QtWidgets.QGroupBox(self.syst_tab)
        self.box_rsettings.setObjectName("box_rsettings")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.box_rsettings)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_15 = QtWidgets.QLabel(self.box_rsettings)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.box_rsettings)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.input_rpath = QtWidgets.QLineEdit(self.box_rsettings)
        self.input_rpath.setMinimumSize(QtCore.QSize(150, 0))
        self.input_rpath.setObjectName("input_rpath")
        self.gridLayout_8.addWidget(self.input_rpath, 0, 1, 1, 1)
        self.button_path = QtWidgets.QPushButton(self.box_rsettings)
        self.button_path.setEnabled(True)
        self.button_path.setMaximumSize(QtCore.QSize(30, 16777215))
        self.button_path.setObjectName("button_path")
        self.gridLayout_8.addWidget(self.button_path, 0, 2, 1, 1)
        self.input_rvers = QtWidgets.QLineEdit(self.box_rsettings)
        self.input_rvers.setMinimumSize(QtCore.QSize(75, 0))
        self.input_rvers.setMaximumSize(QtCore.QSize(75, 16777215))
        self.input_rvers.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_rvers.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_rvers.setProperty("clearButtonEnabled", False)
        self.input_rvers.setObjectName("input_rvers")
        self.gridLayout_8.addWidget(self.input_rvers, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.box_rsettings)
        self.box_systemres = QtWidgets.QGroupBox(self.syst_tab)
        self.box_systemres.setFlat(False)
        self.box_systemres.setObjectName("box_systemres")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.box_systemres)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label = QtWidgets.QLabel(self.box_systemres)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.box_systemres)
        self.label_6.setLineWidth(1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_13.addWidget(self.label_6, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.input_ram = QtWidgets.QSpinBox(self.box_systemres)
        self.input_ram.setEnabled(False)
        self.input_ram.setMinimum(512)
        self.input_ram.setMaximum(4096)
        self.input_ram.setObjectName("input_ram")
        self.gridLayout_4.addWidget(self.input_ram, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.box_systemres)
        self.label_2.setMinimumSize(QtCore.QSize(40, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.box_systemres)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.avail_ram = QtWidgets.QLabel(self.box_systemres)
        self.avail_ram.setObjectName("avail_ram")
        self.gridLayout_4.addWidget(self.avail_ram, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.box_systemres)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 4, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.box_systemres)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 2, 1, 1)
        self.avail_core = QtWidgets.QLabel(self.box_systemres)
        self.avail_core.setObjectName("avail_core")
        self.gridLayout_4.addWidget(self.avail_core, 1, 3, 1, 1)
        self.input_cpu = QtWidgets.QSpinBox(self.box_systemres)
        self.input_cpu.setEnabled(False)
        self.input_cpu.setMinimum(1)
        self.input_cpu.setMaximum(8)
        self.input_cpu.setObjectName("input_cpu")
        self.gridLayout_4.addWidget(self.input_cpu, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.box_systemres)
        self.gridLayout_11.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.box_usersettings.raise_()
        self.box_serversettings.raise_()
        self.box_rsettings.raise_()
        self.box_systemres.raise_()
        self.tabWidget.addTab(self.syst_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)
        PreferencesDialog.setTabOrder(self.input_username, self.input_password)
        PreferencesDialog.setTabOrder(self.input_password, self.ip_entry)
        PreferencesDialog.setTabOrder(self.ip_entry, self.port_entry)
        PreferencesDialog.setTabOrder(self.port_entry, self.input_rpath)
        PreferencesDialog.setTabOrder(self.input_rpath, self.button_path)
        PreferencesDialog.setTabOrder(self.button_path, self.input_rvers)
        PreferencesDialog.setTabOrder(self.input_rvers, self.input_ram)
        PreferencesDialog.setTabOrder(self.input_ram, self.input_cpu)
        PreferencesDialog.setTabOrder(self.input_cpu, self.settings_buttons)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.box_usersettings.setTitle(_translate("PreferencesDialog", "User Settings"))
        self.label_8.setText(_translate("PreferencesDialog", "Password"))
        self.label_4.setText(_translate("PreferencesDialog", "Username"))
        self.box_serversettings.setTitle(_translate("PreferencesDialog", "Server Settings"))
        self.ip_label.setText(_translate("PreferencesDialog", "Server IP/URL"))
        self.port_label.setText(_translate("PreferencesDialog", "Port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serv_tab), _translate("PreferencesDialog", "Server"))
        self.box_rsettings.setTitle(_translate("PreferencesDialog", "R Settings"))
        self.label_15.setText(_translate("PreferencesDialog", "R Version"))
        self.label_16.setText(_translate("PreferencesDialog", "R Path"))
        self.button_path.setText(_translate("PreferencesDialog", "..."))
        self.box_systemres.setTitle(_translate("PreferencesDialog", "System Resource Allocation"))
        self.label.setText(_translate("PreferencesDialog", "RAM"))
        self.label_6.setText(_translate("PreferencesDialog", "Number of cores"))
        self.label_2.setText(_translate("PreferencesDialog", "MB"))
        self.label_3.setText(_translate("PreferencesDialog", "Total:"))
        self.avail_ram.setText(_translate("PreferencesDialog", "N/A"))
        self.label_5.setText(_translate("PreferencesDialog", "MB"))
        self.label_7.setText(_translate("PreferencesDialog", "Total:"))
        self.avail_core.setText(_translate("PreferencesDialog", "N/A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.syst_tab), _translate("PreferencesDialog", "System"))

