# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_2.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(389, 390)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.get_task = QtWidgets.QWidget()
        self.get_task.setObjectName("get_task")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.get_task)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.avaliable_tasks = QtWidgets.QLabel(self.get_task)
        self.avaliable_tasks.setEnabled(False)
        self.avaliable_tasks.setObjectName("avaliable_tasks")
        self.gridLayout_2.addWidget(self.avaliable_tasks, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.get_task)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 4, 1, 1)
        self.connect_status = QtWidgets.QLabel(self.get_task)
        self.connect_status.setEnabled(False)
        self.connect_status.setObjectName("connect_status")
        self.gridLayout_2.addWidget(self.connect_status, 0, 2, 1, 1)
        self.connect_button = QtWidgets.QPushButton(self.get_task)
        self.connect_button.setObjectName("connect_button")
        self.gridLayout_2.addWidget(self.connect_button, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.get_task)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 7, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.get_task)
        self.groupBox.setEnabled(False)
        self.groupBox.setAccessibleName("")
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.number_of_tasks = QtWidgets.QSpinBox(self.groupBox)
        self.number_of_tasks.setEnabled(False)
        self.number_of_tasks.setWrapping(False)
        self.number_of_tasks.setFrame(True)
        self.number_of_tasks.setReadOnly(True)
        self.number_of_tasks.setKeyboardTracking(False)
        self.number_of_tasks.setProperty("showGroupSeparator", False)
        self.number_of_tasks.setMinimum(1)
        self.number_of_tasks.setMaximum(5)
        self.number_of_tasks.setDisplayIntegerBase(10)
        self.number_of_tasks.setObjectName("number_of_tasks")
        self.horizontalLayout.addWidget(self.number_of_tasks)
        self.run_button = QtWidgets.QPushButton(self.groupBox)
        self.run_button.setEnabled(False)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout.addWidget(self.run_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 8)
        self.tabWidget.addTab(self.get_task, "")
        self.submit_task = QtWidgets.QWidget()
        self.submit_task.setObjectName("submit_task")
        self.tabWidget.addTab(self.submit_task, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(178, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.quit_button = QtWidgets.QPushButton(self.centralWidget)
        self.quit_button.setMinimumSize(QtCore.QSize(25, 0))
        self.quit_button.setIconSize(QtCore.QSize(64, 16))
        self.quit_button.setObjectName("quit_button")
        self.horizontalLayout_5.addWidget(self.quit_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 389, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setCheckable(False)
        self.actionSettings.setEnabled(True)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicense_Information = QtWidgets.QAction(MainWindow)
        self.actionLicense_Information.setObjectName("actionLicense_Information")
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionLicense_Information)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ROctopus Client"))
        self.avaliable_tasks.setText(_translate("MainWindow", "N/A"))
        self.label.setText(_translate("MainWindow", "Available tasks:"))
        self.connect_status.setText(_translate("MainWindow", "No."))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "Connected:"))
        self.groupBox.setTitle(_translate("MainWindow", "Run settings:"))
        self.label_5.setText(_translate("MainWindow", "Number of tasks:"))
        self.run_button.setText(_translate("MainWindow", "Run!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.get_task), _translate("MainWindow", "Get Tasks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.submit_task), _translate("MainWindow", "Submit Tasks"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About ROctopus"))
        self.actionLicense_Information.setText(_translate("MainWindow", "License Information"))
