from PyQt5 import QtCore, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(412, 415)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.input_cpu = QtWidgets.QSpinBox(self.groupBox_2)
        self.input_cpu.setObjectName("input_cpu")
        self.gridLayout_4.addWidget(self.input_cpu, 1, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 5, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 6, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 4, 1, 1)
        self.input_ram = QtWidgets.QSpinBox(self.groupBox_2)
        self.input_ram.setObjectName("input_ram")
        self.gridLayout_4.addWidget(self.input_ram, 0, 1, 1, 1)
        self.system_ram = QtWidgets.QLabel(self.groupBox_2)
        self.system_ram.setObjectName("system_ram")
        self.gridLayout_4.addWidget(self.system_ram, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 3)
        self.system_cpu = QtWidgets.QLabel(self.groupBox_2)
        self.system_cpu.setObjectName("system_cpu")
        self.gridLayout_4.addWidget(self.system_cpu, 1, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 8, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.settings_buttons = QtWidgets.QDialogButtonBox(Dialog)
        self.settings_buttons.setAcceptDrops(False)
        self.settings_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.settings_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.settings_buttons.setCenterButtons(False)
        self.settings_buttons.setObjectName("settings_buttons")
        self.gridLayout_2.addWidget(self.settings_buttons, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.input_username = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_username.setObjectName("input_username")
        self.gridLayout_6.addWidget(self.input_username, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.input_password = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_password.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.input_password.setClearButtonEnabled(False)
        self.input_password.setObjectName("input_password")
        self.gridLayout_6.addWidget(self.input_password, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(165, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 3, 1, 1)
        self.ip_label = QtWidgets.QLabel(self.groupBox)
        self.ip_label.setObjectName("ip_label")
        self.gridLayout.addWidget(self.ip_label, 0, 0, 1, 1)
        self.ip_entry = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_entry.sizePolicy().hasHeightForWidth())
        self.ip_entry.setSizePolicy(sizePolicy)
        self.ip_entry.setMinimumSize(QtCore.QSize(15, 0))
        self.ip_entry.setObjectName("ip_entry")
        self.gridLayout.addWidget(self.ip_entry, 0, 1, 1, 2)
        self.port_label = QtWidgets.QLabel(self.groupBox)
        self.port_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 1, 0, 1, 1)
        self.port_entry = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_entry.sizePolicy().hasHeightForWidth())
        self.port_entry.setSizePolicy(sizePolicy)
        self.port_entry.setMinimumSize(QtCore.QSize(80, 0))
        self.port_entry.setMaximumSize(QtCore.QSize(45, 16777215))
        self.port_entry.setObjectName("port_entry")
        self.gridLayout.addWidget(self.port_entry, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "System Resource Allocation"))
        self.label.setText(_translate("Dialog", "RAM"))
        self.label_7.setText(_translate("Dialog", "Total:"))
        self.label_5.setText(_translate("Dialog", "MB"))
        self.label_3.setText(_translate("Dialog", "Total:"))
        self.system_ram.setText(_translate("Dialog", "N/A"))
        self.label_6.setText(_translate("Dialog", "Number of cores:"))
        self.system_cpu.setText(_translate("Dialog", "N/A"))
        self.label_2.setText(_translate("Dialog", "MB"))
        self.groupBox_3.setTitle(_translate("Dialog", "User Settings"))
        self.label_8.setText(_translate("Dialog", "Password"))
        self.label_4.setText(_translate("Dialog", "User Name"))
        self.groupBox.setTitle(_translate("Dialog", "Server Settings"))
        self.ip_label.setText(_translate("Dialog", "Server IP:"))
        self.port_label.setText(_translate("Dialog", "Port"))


class SettingsDialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.InitUi()

        self.ui.ip_entry.setInputMask('000.000.000.000')
        self.ui.port_entry.setInputMask('00000')

    def getValues(self):
        return({
            'username' : self.ui.input_username.text(),
            'pw' : self.ui.input_password.text(), # No way!
            'server_ip' : self.ui.ip_entry.text(),
            'port' : self.ui.port_entry.text(),
            'sys_ram' : self.ui.input_ram.value(),
            'sys_cores' : self.ui.input_cpu.value()
        })

    def InitUi(self):
        self.ui.settings_buttons.accepted.connect(self.accept)
        self.ui.settings_buttons.rejected.connect(self.reject)
        # self.show()
